version: '3'

tasks:
  install:
    cmds:
      - pip install uwsgi
      - pip install Flask
      - pip install sealights-python-agent==1.4.6
  scan:
    cmds:
      - sl-python config --appname python-uwsgi-example --tokenfile ./sltoken.txt
      - sl-python scan
  run:
    env:
#      SL_DEBUG: false
      SL_LAB_ID: some-lab-id
    cmds:
      - sl-python run python ./app.py
  uwsgi:
    cmds:
      - uwsgi --http 0.0.0.0:9092 --module app:APP --enable-threads  --master --single-interpreter --import python_agent.init
